config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :branches do
    resources :documents do
      resources :revisions
    end
  end
  get '/branches/:branch_id/branch_off/documents' => 'branches#branch_off', as: :branch_off
  get '/about' => 'pages#about'
  root 'pages#home'

end

app/models/branch.rb
class Branch < ActiveRecord::Base
  belongs_to :repository

  belongs_to :parent, inverse_of: :children, class_name: "Branch"
  has_many :children, inverse_of: :parent, class_name: "Branch", foreign_key: "parent_id", dependent: :destroy
  
  has_many :documents, dependent: :destroy
  has_many :revisions, dependent: :destroy

  accepts_nested_attributes_for :documents, reject_if: proc { |attr| attr[:title].blank? }, allow_destroy: true
  accepts_nested_attributes_for :revisions, reject_if: proc { |attr| attr[:summary, :body].blank? }, allow_destroy: true

  validates :name, presence: true

  def to_s
    name
  end
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  before_action :set_branch, only: [:show, :edit, :update, :destroy]

  # GET /branches
  # GET /branches.json
  def index
    @branches = Branch.all
  end

  # GET /branches/1
  # GET /branches/1.json
  def show
  end

  # GET /branches/new
  def new
    @branch = Branch.new
    @branch.documents.build
    @branch.documents.each { |d| d.revisions.build }
  end

  # GET /branches/1/edit
  def edit
    @branch = Branch.find(params[:id])
    @old_branch = Branch.find(params[:id])
    @documents = @branch.documents
  end

  # POST /branches
  # POST /branches.json
  def create
    @branch = Branch.new(branch_params)

    respond_to do |format|
      if @branch.save
        format.html { redirect_to @branch, notice: 'Branch was successfully created.' }
        format.json { render :show, status: :created, location: @branch }
      else
        format.html { render :new }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /branches/1
  # PATCH/PUT /branches/1.json
  def update
    respond_to do |format|
      if @branch.update(branch_params)
        format.html { redirect_to @branch, notice: 'Branch was successfully updated.' }
        format.json { render :show, status: :ok, location: @branch }
      else
        format.html { render :edit }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /branches/1
  # DELETE /branches/1.json
  def destroy
    @branch.destroy
    respond_to do |format|
      format.html { redirect_to branches_url, notice: 'Branch was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def branch_off
    @old_branch = Branch.find(params[:branch_id])
    @branch = Branch.new
    @branch.name = "Off-#{@old_branch.name}"
    @branch.parent_id = @old_branch.id
    @branch.save

    @old_documents = Document.where(branch_id: @old_branch)

    @old_documents.each do |doc|
      new_doc = Document.new
      new_doc.title = doc.title
      new_doc.branch_id = @branch.id
      new_doc.save

      new_first_rev = doc.revisions.last.dup
      new_first_rev.parent_id = doc.revisions.last.id
      new_first_rev.document_id = new_doc.id
      new_first_rev.save
    end
    
    redirect_to edit_branch_path(@branch)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_branch
      @branch = Branch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def branch_params
      params.require(:branch).permit(:name, :id, :parent_id, documents_attributes: [:id, :title, revisions_attributes: [:root, :parent_id, :summary, :body, :tags, :commit_message, :status, :document_id]])
    end
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/views/branches/_form.html.erb
<%= form_for(@branch) do |f| %>
  
  <div class="form-group">
    <%= f.label :name, "Branch Name, e.g. 'Main'" %>
    <%= f.text_field :name, class: 'form-control'%>
  </div>

  <%= f.fields_for :documents do |ff| %>
    <div class="form-group">
      <%= ff.label :title %>
      <%= ff.text_field :title, class: 'form-control' %>
    </div>

    <%= ff.fields_for :revisions do |fff| %>
      <div class="form-group">
        <%= fff.label :summary %>
        <%= fff.text_area :summary, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= fff.label :body, "Main Text" %>
        <%= fff.text_area :body, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= fff.label :tags %>
        <%= fff.text_field :tags, class: 'form-control' %>
      </div>

      <% if @current_revision %>
        <%= fff.hidden_field :parent_id, value: @current_revision.id %>
      <% end %>

      <%= f.submit 'Save as draft', class: 'btn btn-default' %>

      <div>
        </br>
        <p><h4><strong></strong>OR add a message and publish this text:</strong></h4></p>
      </div>

      <div class="form-group">
        <%= fff.label :commit_message, "Important changes since the last published version of this text (if there is one)" %>
        <%= fff.text_field :commit_message, class: 'form-control' %>
      </div>

      <%= f.submit 'Publish', class: 'btn btn-primary'%>
      
    <% end %>

  <% end %>
  
<% end %>

app/views/branches/edit.html.erb
<h1>Editing Branch "<%= @branch.name %>"</h1>

<%= form_for(@branch) do |f| %>
  
  <div class="form-group">
    <%= f.label :name, "Edit Branch Name" %>
    <%= f.text_field :name, class: 'form-control'%>
  </div>

  <%= f.submit 'Save', class: 'btn btn-primary'%>
<% end %>

<table>
  <thead>
    <tr>
      <th><h3>Documents on this Branch</h3></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

		<% @branch.documents.each do |document| %>
			<%= render 'documents/docs_list', document: document %>
		<% end %>
	</tbody>
</table>

<br>

<%= link_to 'Show', @branch %> |
<%= link_to 'Back', branches_path %>
<br>
<%= link_to 'Branch Off', branch_off_url(@branch.id) %>

app/views/branches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Branches</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Parent ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @branches.each do |branch| %>
      <tr>
        <td><%= branch.name %></td>
        <td>[<%= branch.parent_id %>]</td>
        <td><%= link_to 'Show', branch %></td>
        <td><%= link_to 'Edit', edit_branch_path(branch) %></td>
        <td><%= link_to 'Destroy', branch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Branch', new_branch_path %>

app/views/branches/new.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<h1>New Branch</h1>
		<div class="well">
			<%= render 'form' %>
		</div>
		<%= link_to 'Back', branches_path %>
	</div>
</div>

app/views/branches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
	<h1>Branch: <%= @branch.name %></h1>
</p>

<p>
	<h3>Documents:</h3>
	<% if @branch.documents.any? %>
		<ul>
			<% @branch.documents.each do |document| %>
				<li><%= link_to document, branch_document_path(@branch.id, document.id) %></li>
			<% end %>
		</ul>
	<% else %>
		<p>Currently, there are no documents on this branch.</p>
	<% end %>
</p>

<p>
	<%= link_to 'Add a document to this branch', new_branch_document_path(@branch.id) %>
</p>

<br>

<p>
	<% if @branch.parent %>
		<h4>Parent Branch: <%= link_to @branch.parent, branch_path(@branch.parent.id) %></h4>	
	<% end %>	
</p>

<p>
	<% if @branch.children.any? %>
		<h4>Branched-off:</h4>
		<ul>
			<% @branch.children.each do |child| %>
				<li><%= link_to child, branch_path(child.id) %>  --> <%= link_to 'Show differences' %></li>
			<% end %>	
		</ul>
	<% end %>
</p>

<br>

<p>
	<%= link_to 'Edit', edit_branch_path(@branch) %> |
	<%= link_to 'Back', branches_path %>
</p>