config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :branches do
    resources :documents do
      resources :revisions
    end
  end
  get '/branches/:branch_id/branch_off/documents' => 'branches#branch_off', as: :branch_off
  get '/about' => 'pages#about'
  root 'pages#home'

end

app/models/revision.rb
class Revision < ActiveRecord::Base
  belongs_to :branch
  belongs_to :document
  belongs_to :parent, inverse_of: :children, class_name: "Revision"
  has_many :children, inverse_of: :parent, class_name: "Revision", foreign_key: "parent_id"

  validates :summary, presence: true
  validates :body, presence: true
  
  before_save :reassign_parent_and_delete_obsolete_drafts_if_necessary

  protected
    def reassign_parent_and_delete_obsolete_drafts_if_necessary
      obsolete_drafts = []
      if self.status == "publish"
        while self.parent && self.parent.status == "draft"
          obsolete_drafts.push(self.parent)
          self.parent_id = self.parent.parent_id
        end
      end
      obsolete_drafts.each { |draft| draft.delete }
    end

end

app/controllers/revisions_controller.rb
class RevisionsController < ApplicationController
  def new
    @revision = Revision.new
    @document = Document.find(params[:document_id])
    @branch = Branch.find(params[:branch_id])
  end

  def create
    @revision = Revision.new(revision_params)

    if @revision.save
      flash[:success] = 'Revision saved.'
      redirect_to edit_revision_path(@revision.id)
    else
      flash[:danger] = 'Error occurred, revision has not been saved.'
      redirect_to new_revision_path
    end
  end

  def index
    @branch = Branch.find(params[:branch_id])
    @document = Document.find(params[:document_id])
    @revisions = Revision.where(document_id: @document)
  end

  def show
    @branch = Branch.find(params[:branch_id])
    @document = Document.find(params[:document_id])
    @current_revision = Revision.find(params[:id])
  end

  def edit
    @branch = Branch.find(params[:branch_id])
    @document = Document.find(params[:document_id])
    @revision = Revision.find(params[:id])
    @current_revision = Revision.find(params[:id])
  end

  def update
    @revision = Revision.new(revision_params)
    @revision.status = "draft" if save_as_draft?
    @revision.status = "publish" if save_as_publish?
    @revision.document_id = params[:document_id] # Why does revision_params not
    # cover this line?
    
    if @revision.status == "publish" && @revision.save
      flash[:success] = 'Revision published!'
    elsif @revision.save
      flash[:success] = 'Revision saved as draft.'
    else
      flash[:danger] = 'Error occurred, revision has not been saved.'
      @revision = Revision.find(params[:id])
      @revision.update(revision_params)
    end

    redirect_to edit_branch_document_revision_path(params[:branch_id], params[:document_id], @revision.id)
  end

  private
    def set_revision
      @revision = Revision.find(params[:id])
      @document = Document.find(params[:document_id])
      @branch = Branch.find(params[:branch_id])
    end

    def revision_params
      params.require(:revision).permit(:root, :parent_id, :summary, :body, :tags, :commit_message, :status, :document_id)
    end

    def save_as_draft?
      params[:commit] == "Save as draft"
    end

    def save_as_publish?
      params[:commit] == "Publish"
    end
end

app/views/revisions/_form.html.erb
<%= form_for [@branch, @document, @revision] do |f| %>
	<div class="form-group">
		<%= f.label :summary %>
		<%= f.text_area :summary, class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :body, "Main Text" %>
		<%= f.text_area :body, class: 'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :tags %>
		<%= f.text_field :tags, class: 'form-control' %>
	</div>
	<% if @current_revision %>
			<%= f.hidden_field :parent_id, value: @current_revision.id %>
	<% end %>

	<%= f.submit 'Save as draft', class: 'btn btn-default' %>

	<% if @current_revision %>
		<div>
			</br>
			<p><strong>OR save a new significant revision of your text:</strong></p>
		</div>
		
		<div class="form-group">
			<%= f.label :commit_message, "Important changes since the last significant revision - ALL DRAFTS SINCE THE LAST SIGNIFICANT REVISION WILL BE DELETED!" %>
			<%= f.text_field :commit_message, class: 'form-control' %>
		</div>

		<%= f.submit 'Save new revision', class: 'btn btn-primary' %>

	<% end %>

<% end %>

app/views/revisions/edit.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<h1>Editing Revision</h1>
		<div class="well">
			
			<%= render 'form' %>
				
		</div>
	</div>
</div>

app/views/revisions/index.html.erb
<h1>Revisions for Document: <%= @document.title %></h1>
<h4>-- Branch: <%= @branch.name %></h4>

<br>

<table>
	<tr>
		<th>ID</th>
		<th>Root?</th>
		<th>Parent ID</th>
		<th>Status</th>
		<th>Summary</th>
		<th>Main Text</th>
		<!-- <th>Tags</th> -->
		<th>Commit Message</th>
		<th>Created</th>
		<!-- <th>Updated</th> -->
	</tr>

<% @revisions.each do |revision| %>
	<tr>
		<td><%= revision.id %></td>
		<td><%= revision.root %></td>
		<td><%= revision.parent_id %></td>
		<td><%= revision.status %></td>
		<td><%= revision.summary %></td>
		<td><%= revision.body %></td>
		<!-- <td><%= revision.tags %></td> -->
		<td><%= revision.commit_message %></td>
		<td><%= revision.created_at.to_date.inspect %></td>
		<!-- <td><%= revision.updated_at.to_date.inspect %></td> -->
		<td><%= link_to 'Show', branch_document_revision_path(revision.document.branch_id, revision.document_id, revision.id) %></td>
	</tr>
<% end %>
</table>

<!--<%= link_to "New revision", new_branch_document_revision_path %>-->

app/views/revisions/new.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<h1>Start a new text:</h1>
		<div class="well">
			
			<%= render 'form' %>
				
		</div>
	</div>
</div>

app/views/revisions/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Revision: <%= @current_revision.id %></h1>

<h4>-- Document: <%= @document.title %></h4>

<h4>-- Branch: <%= @branch.name %></h4>

<br>

<p>
	<strong>Summary:</strong>
  <%= @current_revision.summary %>
</p>

<p>
	<strong>Main Text:</strong>
  <%= @current_revision.body %>
</p>

<p>
	<strong>Tags:</strong>
  <%= @current_revision.tags %>
</p>

<p>
	<strong>Created:</strong>
  <%= @current_revision.created_at.to_date.inspect %>
</p>

<p>
	<strong>Commit Message:</strong>
  <%= @current_revision.commit_message %>
</p>

<p>
	<strong>Status:</strong>
  <%= @current_revision.status %>
</p>

<!--<%= link_to 'Edit', edit_branch_document_path(@document.branch_id, @document.id) %> |-->
<%= link_to 'Back to all revisions', branch_document_revisions_path(@document.branch_id, @document.id) %>