config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :branches do
    resources :documents do
      resources :revisions
    end
  end
  get '/branches/:branch_id/branch_off/documents' => 'branches#branch_off', as: :branch_off
  get '/about' => 'pages#about'
  root 'pages#home'

end

app/models/document.rb
class Document < ActiveRecord::Base
  belongs_to :branch
  has_many :revisions, dependent: :destroy
  has_one :current_revision, class_name: "Revision", foreign_key: "document_id"
  accepts_nested_attributes_for :revisions, reject_if: proc { |attr| attr[:body].blank? || attr[:summary].blank? }, allow_destroy: true
  
  validates :title, presence: true

  def to_s
    title
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @branch = Branch.find(params[:branch_id])
    @documents = Document.where(branch_id: @branch)
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    @branch = Branch.find(params[:branch_id])
    @document = Document.find(params[:id])
    @revisions = Revision.where(document_id: @document)
    @current_revision = Revision.where(document_id: @document).last
  end

  # GET /documents/new
  def new
    @branch = Branch.find(params[:branch_id])
    @document = Document.new
    @current_revision = @document.revisions.build
  end

  # GET /documents/1/edit
  def edit
    @document = Document.find(params[:id])
    @revisions = @document.revisions
    @current_revision = @document.revisions[-1]
  end

  # POST /documents
  # POST /documents.json
  def create
    @document = Document.new(document_params)
    @branch = Branch.find(params[:branch_id])
    @document.branch = @branch
    @revisions = @document.revisions
    
    respond_to do |format|
      if @document.save
        format.html { redirect_to branch_document_url(@branch, @document), notice: 'Document was successfully created.' }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to branch_document_url(@branch, @document), notice: 'Document was successfully updated.' }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url, notice: 'Document was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
      @branch = Branch.find(params[:branch_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:title, :id, revisions_attributes: [:root, :parent_id, :summary, :body, :tags, :commit_message, :status, :document_id])
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_docs_list.html.erb
<tr>
  <td><%= document.title %></td>
  <td><%= link_to 'Show', branch_document_path(document.branch_id, document.id) %></td>
  <% if controller_name != 'documents' %>
	  <td><%= link_to 'Edit', edit_branch_document_path(document.branch_id, document.id) %></td>
	  <td><%= link_to 'Destroy', branch_document_path(document.branch_id, document.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<% end %>
</tr>

app/views/documents/_form.html.erb
<%= form_for [@branch, @document] do |f| %>

  <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>
  </div>
  <%= f.submit 'Save Title', class: 'btn btn-default' %>
<% end %>

<%= form_for [@branch, @document, @current_revision] do |f| %>

    <div class="form-group">
      <%= f.label :summary %>
      <%= f.text_area :summary, value: @current_revision.summary, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :body, "Main Text" %>
      <%= f.text_area :body, value: @current_revision.body, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :tags %>
      <%= f.text_field :tags, value: @current_revision.tags, class: 'form-control' %>
    </div>

    <% if @current_revision %>
      <%= f.hidden_field :parent_id, value: @current_revision.id %>
    <% end %>

    <%= f.submit 'Save as draft', class: 'btn btn-default' %>

    <div>
      </br>
      <p><h4><strong></strong>OR add a message and publish this text:</strong></h4></p>
    </div>

    <div class="form-group">
      <%= f.label :commit_message, "Important changes since the last published version of this text (if there is one)" %>
      <%= f.text_field :commit_message, value: @current_revision.commit_message, class: 'form-control' %>
    </div>

    <%= f.submit 'Publish', class: 'btn btn-primary'%>

<% end %>

app/views/documents/edit.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<h1>Editing Document</h1>
		<div class="well">

			<%= render 'form' %>

		</div>

			<%= link_to 'Show', branch_document_path(@document.branch_id, @document.id) %> |
			<%= link_to 'Back', branch_documents_path(@document.branch_id) %>
		
	</div>
</div>

app/views/documents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Documents on Branch <%= @branch.name %></h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @documents.each do |document| %>
      <%= render 'documents/docs_list', document: document %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Document', new_branch_document_path %>

app/views/documents/new.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<h1>New Document on Branch <%= @branch.name %></h1>
		<div class="well">
			<%= form_for [@branch, @document] do |f| %>

			  <div class="form-group">
			      <%= f.label :title %>
			      <%= f.text_field :title, class: 'form-control' %>
			  </div>
			  
			  <%= f.fields_for :revisions do |ff| %>
			  	<div class="form-group">
			      <%= ff.label :summary %>
			      <%= ff.text_area :summary, value: @current_revision.summary, class: 'form-control' %>
			    </div>

			    <div class="form-group">
			      <%= ff.label :body, "Main Text" %>
			      <%= ff.text_area :body, value: @current_revision.body, class: 'form-control' %>
			    </div>

			    <div class="form-group">
			      <%= ff.label :tags %>
			      <%= ff.text_field :tags, value: @current_revision.tags, class: 'form-control' %>
			    </div>
			  <% end %>

			  <%= f.submit 'Save Document', class: 'btn btn-default' %>
			<% end %>
		</div>
		<%= link_to 'Back', branch_documents_path %>
	</div>
</div>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Document: <%= @document.title %></h1>

<h4>-- Branch: <%= @branch.name %></h4>

<br>

<p>
	<strong>Summary:</strong>
  <%= @current_revision.summary %>
</p>

<p>
	<strong>Main Text:</strong>
  <%= @current_revision.body %>
</p>

<p>
	<strong>Tags:</strong>
  <%= @current_revision.tags %>
</p>

<p>
	<strong>Created:</strong>
  <%= @current_revision.created_at.to_date.inspect %>
</p>

<p>
	<strong>Commit Message:</strong>
  <%= @current_revision.commit_message %>
</p>

<p>
	<strong>Status:</strong>
  <%= @current_revision.status %>
</p>

<%= link_to 'Edit', edit_branch_document_path(@document.branch_id, @document.id) %> |
<%= link_to 'Show all revisions', branch_document_revisions_path(@document.branch_id, @document.id) %> |
<%= link_to 'Back', branch_documents_path %>